In [1]:
import torch

In [41]:
for i in range(9,14):
    file = f'./data/CIKM22Competition/{i}/train.pt'
    data = torch.load(file)
    file2 = f'./data/CIKM22Competition/{i}/val.pt'
    data2 = torch.load(file2)
    targets = torch.Tensor([])
    for sample in data:
        y = sample.y
        targets = torch.concat((targets,y),dim=0)
    for sample in data2:
        y = sample.y
        targets = torch.concat((targets,y),dim=0)
    std,mean = torch.std_mean(targets,dim=0)
    print(i,std,mean)

9 tensor([0.3787]) tensor([1.5360])
10 tensor([0.1307, 0.1014, 0.1209, 0.1307, 0.1307, 0.1307, 0.1071, 0.1372, 0.1423,
        0.1046]) tensor([0.2142, 0.3929, 0.4393, 0.2142, 0.2142, 0.2142, 0.3723, 0.7066, 0.5433,
        0.3379])
11 tensor([1.2011]) tensor([2.1919])
12 tensor([2.1230]) tensor([-3.1072])
13 tensor([0.0985, 0.0482, 0.0792, 0.1227, 0.0987, 0.0606, 0.0979, 0.0658, 0.1273,
        0.1189, 0.1139, 0.0992]) tensor([0.3603, 0.8600, 0.3424, 0.5235, 0.3608, 0.4221, 0.3575, 0.5763, 0.5012,
        0.4644, 0.4353, 0.6247])


In [25]:
for i in range(1,14):
    file = f'./data/CIKM22Competition/{i}/train.pt'
    data = torch.load(file)
    num_1 = 0
    num_0 = 0
#     for sample in data:
#         if sample.y.item() == 1:
#             num_1 += 1
#         else:
#             num_0 += 1
    print(len(data))
#     print(i,num_0/len(data),num_1/len(data))
#     file = f'./data/CIKM22Competition/{i}/val.pt'
#     data = torch.load(file)
#     num_1 = 0
#     num_0 = 0
#     for sample in data:
#         if sample.y.item() == 1:
#             num_1 += 1
#         else:
#             num_0 += 1
#     print(len(data))
#     print(i,num_0/len(data),num_1/len(data))
#     file = f'./data/CIKM22Competition/{i}/test.pt'
#     data = torch.load(file)
#     num_1 = 0
#     num_0 = 0
#     for sample in data:
#         if sample.y.item() == 1:
#             num_1 += 1
#         else:
#             num_0 += 1
#     print(len(data))
#     print(i,num_0/len(data),num_1/len(data))

1249
181
2219
101
188
1101
2228
777
134706
109392
2268
608
70648


In [8]:
transform = [['Normalize', 
              {'mean': [0.1308, 0.1011, 0.1208, 0.1308, 0.1308, 0.1308, 0.1069, 0.1372, 0.1423,0.1044],
               'std': [0.2141, 0.3929, 0.4392, 0.2141, 0.2141, 0.2141, 0.3723, 0.7067, 0.5434,0.3379]
              }
             ]]
y = torch.rand(10,10)
if len(transform)==1 and transform[0][0] == "Normalize":
    mean = torch.Tensor(transform[0][1]['mean'])
    std = torch.Tensor(transform[0][1]['std'])
    label = (y-mean)/std
    print(label)
    

tensor([[ 1.8576,  0.8056,  0.8500,  2.3081,  3.8867,  3.6434,  1.5454,  1.1345,
         -0.1141,  0.0781],
        [ 1.7142,  0.4453,  0.2575,  3.3766, -0.2550, -0.0392,  0.2714,  0.4827,
          1.2848,  1.1765],
        [-0.2493,  0.9632,  1.5260,  3.1759,  0.0879,  2.3773,  0.2122, -0.1010,
         -0.1163,  1.3427],
        [ 0.2754,  2.0910, -0.0251,  1.7946,  3.3723,  2.1337,  1.4855,  1.0659,
          0.2719,  0.8483],
        [ 3.6802,  2.1860,  0.9514,  3.7902,  2.3190,  2.1569,  1.9102,  0.5939,
          1.2341, -0.2038],
        [ 0.7249, -0.1630,  1.4073,  2.3141, -0.5853,  2.4374,  0.6880,  0.2614,
          0.2223,  0.4697],
        [ 0.3168,  1.9469,  0.2996,  2.2608,  2.3841,  1.3365,  0.4413,  0.7686,
          0.9525,  0.8891],
        [ 1.6069,  0.5388,  1.0862,  2.0755,  1.0756,  3.0444,  0.3426,  0.3526,
          0.1522,  1.2976],
        [ 2.9090,  1.8712,  0.3730,  0.8645,  1.2292, -0.5926,  2.3286,  0.0046,
          1.3082,  1.9149],
        [ 1.3667, -

In [16]:
import numpy as np
print(label)
np.argmax(label,axis=1)

[[[ 1.8576273 ]
  [ 0.80559486]
  [ 0.8500021 ]
  [ 2.3080983 ]
  [ 3.8866618 ]
  [ 3.6433964 ]
  [ 1.5453985 ]
  [ 1.1344826 ]
  [-0.11405271]
  [ 0.07814799]]

 [[ 1.71418   ]
  [ 0.44534463]
  [ 0.25748965]
  [ 3.376626  ]
  [-0.25500396]
  [-0.03920843]
  [ 0.27141914]
  [ 0.48269227]
  [ 1.2848246 ]
  [ 1.1765109 ]]

 [[-0.24925007]
  [ 0.96324426]
  [ 1.5259885 ]
  [ 3.1758912 ]
  [ 0.08791205]
  [ 2.377269  ]
  [ 0.21221873]
  [-0.10101835]
  [-0.11634716]
  [ 1.3426818 ]]

 [[ 0.2753696 ]
  [ 2.091038  ]
  [-0.02513991]
  [ 1.7946135 ]
  [ 3.372299  ]
  [ 2.1336935 ]
  [ 1.485505  ]
  [ 1.0658524 ]
  [ 0.27194968]
  [ 0.8483234 ]]

 [[ 3.680169  ]
  [ 2.1859634 ]
  [ 0.95142704]
  [ 3.790172  ]
  [ 2.3189802 ]
  [ 2.1569386 ]
  [ 1.9102478 ]
  [ 0.59393996]
  [ 1.234078  ]
  [-0.20383948]]

 [[ 0.72494787]
  [-0.16297987]
  [ 1.407295  ]
  [ 2.3140953 ]
  [-0.5852922 ]
  [ 2.437356  ]
  [ 0.688038  ]
  [ 0.26136622]
  [ 0.22226119]
  [ 0.46968696]]

 [[ 0.31680948]
  [ 1.946949

array([[4],
       [3],
       [3],
       [4],
       [3],
       [5],
       [4],
       [5],
       [0],
       [4]])

In [31]:
prediction_csv = './exp/local_gin_on_cikmcup_lr0.1_lstep1_/sub_exp_20220831000609/prediction.csv'
pred_1 = './exp/local_gin_on_cikmcup_lr0.1_lstep30_/sub_exp_20220830135033/prediction.csv'
pred_2 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220829234917/prediction.csv'
pred_3 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220830150335/prediction.csv'
pred_4 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220830153345/prediction.csv'
pred_5 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220829183442/prediction.csv'
pred_6 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220830165846/prediction.csv'
pred_7 = './exp/local_gin_on_cikmcup_lr0.1_lstep30_/sub_exp_20220830173523/prediction.csv'
pred_8 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220830183924/prediction.csv'
pred_9 = './exp/local_gin_on_cikmcup_lr0.1_lstep5_/sub_exp_20220829164011/prediction.csv'
pred_10 = './exp/local_gin_on_cikmcup_lr0.1_lstep30_/sub_exp_20220826131854/prediction.csv'
pred_11 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220830200321/prediction.csv'
pred_12 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220828181041/prediction.csv'
pred_13 = './exp/local_gin_on_cikmcup_lr0.1_lstep1_/sub_exp_20220830210023/prediction.csv'
new_csv = './exp/local_gin_on_cikmcup_lr0.1_lstep1_/new_prediction.csv'
nf = open(new_csv,'w')
fs = {}
ns = {}
for i in range(1,14):
    fi = open(eval(f'pred_{i}'),'r')
    predi = fi.readlines()
    ns[i] = 0
    fs[i] = predi
    fi.close()
with open(prediction_csv,'r') as f:
    predictions = f.readlines()
    print(predictions[0])
    for prediction in predictions:
        client_id = int(prediction.split(',')[0])
        predi = fs[client_id][ns[client_id]]
        nf.write(predi)
        ns[client_id] += 1
nf.close()

1,0,0



In [37]:
prediction_csv = './exp/local_gin_on_cikmcup_lr0.1_lstep1_/sub_exp_20220901002750/prediction.csv'
pred_1 = './exp/local_gin_on_cikmcup_lr0.1_lstep30_/sub_exp_20220830135033/prediction.csv'
pred_2 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220829234917/prediction.csv'
pred_3 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220830150335/prediction.csv'
pred_4 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220830153345/prediction.csv'
pred_5 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220829183442/prediction.csv'
pred_6 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220830165846/prediction.csv'
pred_7 = './exp/local_gin_on_cikmcup_lr0.1_lstep30_/sub_exp_20220830173523/prediction.csv'
pred_8 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220830183924/prediction.csv'
pred_9 = './exp/local_gin_on_cikmcup_lr0.1_lstep5_/sub_exp_20220829164011/prediction.csv'
pred_10 = './exp/local_gin_on_cikmcup_lr0.1_lstep30_/sub_exp_20220826131854/prediction.csv'
pred_11 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220830200321/prediction.csv'
pred_12 = './exp/local_gin_on_cikmcup_lr0.1_lstep20_/sub_exp_20220828181041/prediction.csv'
pred_13 = './exp/local_gin_on_cikmcup_lr0.1_lstep1_/sub_exp_20220830210023/prediction.csv'
new_csv = './exp/local_gin_on_cikmcup_lr0.1_lstep1_/new_prediction.csv'
nf = open(new_csv,'w')
fs = {}
ns = {}
for i in range(1,14):
    fi = open(eval(f'pred_{i}'),'r')
    predi = fi.readlines()
    ns[i] = 0
    fs[i] = predi
    fi.close()
with open(prediction_csv,'r') as f:
    predictions = f.readlines()
    for prediction in predictions:
        client_id = int(prediction.split(',')[0])
        if client_id in [7,8,9,12]:
            predi = fs[client_id][ns[client_id]]
            nf.write(predi)
            ns[client_id] += 1
        else:
            nf.write(prediction)
nf.close()

In [40]:
prediction_csv = './exp/ditto_finetune_gin_on_cikmcup_lr0.1_lstep1_/sub_exp_20220909000819/prediction.csv'
now_csv = './exp/local_gin_on_cikmcup_lr0.1_lstep1_/new_prediction.csv'
new_csv = './exp/local_gin_on_cikmcup_lr0.1_lstep1_/new_prediction_2.csv'
nf = open(new_csv,'w')
\
fi = open(prediction_csv,'r')
predi = fi.readlines()
fi.close()
i = 0
with open(now_csv,'r') as f:
    predictions = f.readlines()
    for prediction in predictions:
        client_id = int(prediction.split(',')[0])
        if client_id in [1,2,3,4,5,6,7,8,11,12]:
            nf.write(predi[i])
            i += 1
        else:
            nf.write(prediction)
nf.close()
